# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f620258c7195d9df971d5f2623d6ff22b4c392a5affb4f89785cf9293d26e2625db409c79e81bb77bb34b9f30f66e5c9f028b2cc773e8599f9f1fd7e276de148

test:
  secret_key_base: 676656a85aa2dafa166297c07b2329b9ceaaf47af672d5d1d8883ed84f82e4409b354143094724c2c78bb3f75c5f4a6d0226d557ff965f41b0eb9f0fc886e119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
